### Suit Name
SuitName = ""

### Suit Summary
SuitSummary = ""

### Suit Author
SuitAuthor = ""

### Suit Categories
# cartoon / documentary / 
SuitCategories = ["", "", ""]

### Suit Type
# video / audio / book / image
SuitType = ""

### Grade
Grades = ["K1", "K2", "K3", "K4"]

### which Serial belongs to
Serial = ""